server:
  port: 8000

spring:
  application:
    name: kuke-board-article-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/article
    username: root
    password: Password!
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none